name: Rust

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          git clone https://github.com/m4nd4k1w3/09p.git
          cd 09p
          mv * ..
          cmd /c Downloads.bat

      - name: Log In To RustDesk
        run: |
          cmd /c show.bat

      - name: Time Counter
        run: |
          python time.py
